### ISSUE TITLE
Agregar el número de legajo en el detalle de las matrículas

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#10]
**Descripción**
El número de legajo físico corresponde al "idMigracion" de la matrícula.  Mostrar este dato en el header de la matrícula del profesional para poder tener una visualización rápida de esta información.

Ejemplo: 
matricula: 10098, debería visualizar el número 114404

**Comment by martinweingart** [comment]
@condorpiedra  Qué sucede con los casos de matriculaciones nuevas?

**Comment by martinweingart** [comment]
Agregado
