### ISSUE TITLE
Crear boletas de Derecho Anual para un profesional

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#11]
**Descripción**
Se intenta crear un boleta de derecho anual a un profesional para un mes determinado.  Aparece un mensaje de alerta indicando que ya existe una boleta para el mes seleccionado.  Se edita el mes pero el botón de "Guardar" queda cargando y no permite guardar los nuevos cambios.  Hay que salir de la opción y volver a ingresar para completar la operación

**Comment by martinweingart** [comment]
Solucionado.
