### ISSUE TITLE
Cobranza de un volante de pago

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#12]
**Descripción**
Se genera un volante de pago de un derecho de inscripción anual

**Pasos para reproducir el incidente**
1. Generar un volante de pago de un derecho anual de inscripción.
2. Seleccionar el volante y presionar "Pagar".
3. Agregar la forma de pago y presionar Guardar.
4. Ver el error

**Comportamiento Esperado**
Poder asociar un volante con un recibo
![image](https://user-images.githubusercontent.com/19696043/49346031-3e2efb00-f66b-11e8-986e-da7f3b256bd7.png)

**Comment by martinweingart** [comment]
Problema en api rest. Solucionado
