### ISSUE TITLE
Solicitudes - orden por estado

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#2]
**Descripcion**
Cuando se cambiar orden en el listado de solicitudes para listar por estado de forma descendente el listado queda recargando y no muestra inmediatamente las solicitudes

**Pasos**
1. Ingresar en solicitudes en Ver listado 
2. Click en el header de la columna "estado" para visualizar la lista ordenada de forma descendente 

**Comportamiento esperado**
Se desa ver el listado reordenado por estado

**Captura de pantalla**
![image](https://user-images.githubusercontent.com/19696043/42298837-639a8bce-7fde-11e8-9981-dded82fad243.png)

**Comment by martinweingart** [comment]
Solucionado. No tenía en cuenta inconsistencias en la base de datos. Existían solicitudes con profesionales inexistentes.
