### ISSUE TITLE
Crear Legajo Técnico - Visualizar boleta

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#3]
**Descripción**
Se crea un legajo técnico con los datos mínimos y no se visualiza en deudas pendientes la boleta generada

**Pasos**
1. Seleccionar un matricula, ir a "Legajos Técnicos" y presionar crear legajo técnico
2.Cargar los datos de Honorarios y solo aporte neto
3.Click en guardar
4. Presionar Deudas Pendientes para visualizar la boleta
4 Visualizar el mensaje envido

**Captura**
If applicble, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/19696043/42300886-e81f7e90-7fe8-11e8-8e9c-156526e6a572.png)

**Comment by martinweingart** [comment]
Solucionado. No tenia en cuenta inconsistencias en la BD. Existian boletas sin el legajo asociado.
