### ISSUE TITLE
Cobrar una boleta de derecho anual de un nuevo matriculado

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#5]
**Pasos**
1. Seleccionar un matriculado.
2. Click en _Deudas Pendientes_  seleccionar una boleta a pagar
3. Ingresar en Forma de Pago
4. Presionar el botón agregar

**Comportamiento Esperado**
Se desea poder cancelar la boleta pendiente con una forma de pago seleccionada

**Screenshots**
![imagen](https://user-images.githubusercontent.com/19696043/44427133-017d3f00-a567-11e8-8517-96ef78a8a1e8.png)

**Comment by martinweingart** [comment]
Error al intentar transformar el atributo 'titular_cuenta' en mayúscula cuando era indefinido. Se agrego if is not undefined.
