### ISSUE TITLE
Mejor en legajos Técnicos de un matriculado

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#6]
**Descripción**
Visualización de los datos de los legajos de un matriculado

**Pasos**
1. Buscar una matricula y seleccionarla
2. Click en legajos
3. Visualizar el listado de legajos de un matriculado

**Comportamiento esperado**
Alinear el contenido con el encabezado.  Se recomienda no escrollear para poder la opción de edición de un legajo. Se sugiere quitar la posibilidad de modificar el importe debido a que en muchas ocasiones existen volante y boletas generadas

**Capturas de pantalla**
![imagen](https://user-images.githubusercontent.com/19696043/44491339-4ec8e180-a637-11e8-842a-6ba22611892f.png)

**Comment by martinweingart** [comment]
Se acomodaron las columnas
