### ISSUE TITLE
Editar una solicitud de empresa

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#7]
**Descripción**
Se carga una solicitud de empresa con los datos básicos y se intenta editarla

**Pasos**

1. Cargar una solicitud de empresas con los datos básicos
2. Ingresar a solicitudes y presionar editar
3. La paǵina queda cargando

Se sugiere marcar como requerido el cambio de fecha de inicio

![image](https://user-images.githubusercontent.com/19696043/48511305-1818f680-e835-11e8-9593-813e3a85ef79.png)

**Comment by martinweingart** [comment]
Solucionado
