### ISSUE TITLE
Aprobar matrícula de profesional

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#8]
**Descripción**
Se aprueba una matricula de un profesional

**Pasos**
1. Ingresar a las solicitudes pendientes de profesionales
2. Seleccionar una solicitud y elegir la opción "Aprobar"
3. Asignar un número de Acta y tildar la opción "Generar boleta de Inscripción"
4. Presionar el botón "Aprobar"
5. Visualizar la respuesta en la consola

![imagen](https://user-images.githubusercontent.com/19696043/48924649-695e6100-ee99-11e8-96dc-2655565acf5c.png)

**Comment by martinweingart** [comment]
Se probó y funciona correctamente. No se encontró ningún error. De todos modos el mensaje es por problemas en servidor.
