### ISSUE TITLE
Cobranzas - Anular Recibo de un matriculado

### ISSUE THREAD

**Issue by condorpiedra** [argnu/cptn-webapp#9]
**Descripción**
Se ingresa a la cuenta de un profesional matriculado para anular un recibo, que está aplicado a varias boletas.  La operación de anulación se completa y el recibo queda anulado, pero las boletas asociadas no figuran en las deudas pendientes nuevamente

**Pasos**
1. Ingresar a la cuenta de un profesional matriculado
2. Seleccionar un recibo y seleccionar la opción "Anular"
3.  Visualizar las boletas asociadas pendientes de pago pero en la solapa "Deudas Pendientes" no figuran estas boletas

![imagen](https://user-images.githubusercontent.com/19696043/48924880-e559a880-ee9b-11e8-9817-5af2241b8aa0.png)
![imagen](https://user-images.githubusercontent.com/19696043/48924887-03bfa400-ee9c-11e8-8452-03d91c1b2fe6.png)

**Comment by martinweingart** [comment]
Solucionado. No se llamaba a la función de búsqueda de boletas al servidor al seleccionar el tab.
